//! Response types for the Responses API.

use serde::{Deserialize, Serialize};
use serde_json::Value;

use super::{Tool, ToolChoice};

/// The response object returned by POST /v1/responses
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response {
    /// Unique identifier for this response
    pub id: String,

    /// Always "response"
    pub object: &'static str,

    /// Unix timestamp of creation
    pub created_at: i64,

    /// Response status
    pub status: ResponseStatus,

    /// Error information if status is "failed"
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ResponseError>,

    /// Details about incomplete response
    #[serde(skip_serializing_if = "Option::is_none")]
    pub incomplete_details: Option<IncompleteDetails>,

    /// The instructions used
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,

    /// Max output tokens setting
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<u32>,

    /// Model ID used
    pub model: String,

    /// Output items generated by the model (reasoning, messages, tool calls interleaved)
    pub output: Vec<OutputItem>,

    /// Whether parallel tool calls were enabled
    pub parallel_tool_calls: bool,

    /// Previous response ID if this was a continuation
    #[serde(skip_serializing_if = "Option::is_none")]
    pub previous_response_id: Option<String>,

    /// Reasoning configuration (for o-series models)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<ReasoningConfig>,

    /// Whether this response is stored
    pub store: bool,

    /// Temperature used
    pub temperature: f32,

    /// Text format configuration
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<TextConfig>,

    /// Tool choice setting used
    pub tool_choice: ToolChoice,

    /// Tools that were available
    pub tools: Vec<Tool>,

    /// Top-p value used
    pub top_p: f32,

    /// Truncation setting
    #[serde(default)]
    pub truncation: Truncation,

    /// Token usage statistics
    pub usage: Usage,

    /// User identifier (deprecated)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,

    /// Metadata
    #[serde(default, skip_serializing_if = "Value::is_null")]
    pub metadata: Value,
}

impl Response {
    pub const OBJECT: &'static str = "response";
}

/// Response status.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ResponseStatus {
    Completed,
    Failed,
    InProgress,
    Cancelled,
    Queued,
    Incomplete,
}

/// Error information for failed responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseError {
    pub code: String,
    pub message: String,
}

/// Details about why a response is incomplete.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IncompleteDetails {
    pub reason: IncompleteReason,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum IncompleteReason {
    MaxOutputTokens,
    ContentFilter,
}

// ============================================================================
// Output Items - All possible types that can appear in response.output[]
// These can be interleaved: reasoning -> function_call -> message -> reasoning...
// ============================================================================

/// Output item in the response. Multiple types can be interleaved.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OutputItem {
    /// Reasoning/thinking from the model (o-series, DeepSeek R1, etc.)
    Reasoning(ReasoningOutput),

    /// A message from the assistant
    Message(MessageOutput),

    /// A function call request from the model
    FunctionCall(FunctionCallOutput),

    /// A custom tool call (free-form input, not JSON schema)
    CustomToolCall(CustomToolCallOutput),

    /// Web search tool call (built-in)
    WebSearchCall(WebSearchCallOutput),

    /// File search tool call (built-in)
    FileSearchCall(FileSearchCallOutput),

    /// Code interpreter tool call (built-in)
    CodeInterpreterCall(CodeInterpreterCallOutput),

    /// Computer use tool call (built-in)
    ComputerCall(ComputerCallOutput),
}

// ============================================================================
// Reasoning Output
// ============================================================================

/// Reasoning/thinking output from the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningOutput {
    /// Unique ID for this reasoning item
    pub id: String,
    /// Status of this output item
    #[serde(default)]
    pub status: OutputStatus,
    /// Reasoning content (may be empty if hidden)
    #[serde(default)]
    pub content: Vec<ReasoningContent>,
    /// Summary of reasoning (if available)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub summary: Vec<ReasoningSummary>,
    /// Encrypted content for multi-turn (when using store=false)
    #[serde(skip_serializing_if = "Option::is_none")]
    pub encrypted_content: Option<String>,
}

/// Content within reasoning output.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ReasoningContent {
    /// Visible reasoning text
    ReasoningText { text: String },
    /// Redacted reasoning (for hidden chain-of-thought)
    Redacted {},
}

/// Summary of reasoning.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ReasoningSummary {
    SummaryText { text: String },
}

// ============================================================================
// Message Output
// ============================================================================

/// A message output from the assistant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageOutput {
    /// Unique ID for this message
    pub id: String,
    /// Status of this output item
    pub status: OutputStatus,
    /// Always "assistant"
    pub role: OutputRole,
    /// Content of the message
    pub content: Vec<OutputContent>,
}

/// Content within a message output.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum OutputContent {
    /// Text output
    OutputText {
        text: String,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        annotations: Vec<Annotation>,
    },
    /// Refusal (content policy violation)
    Refusal { refusal: String },
}

/// Annotation on text output (citations, file references, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Annotation {
    FileCitation {
        file_id: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        filename: Option<String>,
        index: u32,
    },
    UrlCitation {
        url: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        title: Option<String>,
        index: u32,
    },
    FilePath {
        file_id: String,
        index: u32,
    },
}

// ============================================================================
// Function Call Output
// ============================================================================

/// A function call output from the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCallOutput {
    /// Unique ID for this function call item
    pub id: String,
    /// Call ID to reference when sending results back
    pub call_id: String,
    /// Name of the function to call
    pub name: String,
    /// JSON-encoded arguments
    pub arguments: String,
    /// Status of this output item
    pub status: OutputStatus,
}

// ============================================================================
// Custom Tool Call Output (free-form input)
// ============================================================================

/// Custom tool call with free-form text input (not JSON schema).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomToolCallOutput {
    /// Unique ID for this item
    pub id: String,
    /// Call ID to reference when sending results back
    pub call_id: String,
    /// Name of the custom tool
    pub name: String,
    /// Free-form text input (not JSON)
    pub input: String,
    /// Status of this output item
    pub status: OutputStatus,
}

// ============================================================================
// Built-in Tool Outputs
// ============================================================================

/// Web search tool call output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebSearchCallOutput {
    pub id: String,
    pub status: OutputStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub action: Option<WebSearchAction>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebSearchAction {
    pub query: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub sources: Vec<WebSearchSource>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WebSearchSource {
    pub url: String,
    pub title: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub snippet: Option<String>,
}

/// File search tool call output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileSearchCallOutput {
    pub id: String,
    pub status: OutputStatus,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub results: Vec<FileSearchResult>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileSearchResult {
    pub file_id: String,
    pub filename: String,
    pub score: f32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

/// Code interpreter tool call output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeInterpreterCallOutput {
    pub id: String,
    pub status: OutputStatus,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub outputs: Vec<CodeInterpreterOutput>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum CodeInterpreterOutput {
    Logs { logs: String },
    Image { file_id: String },
}

/// Computer use tool call output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ComputerCallOutput {
    pub id: String,
    pub status: OutputStatus,
    pub action: ComputerAction,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub call_id: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub pending_safety_checks: Option<Vec<SafetyCheck>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ComputerAction {
    Click {
        x: i32,
        y: i32,
        button: String,
    },
    DoubleClick {
        x: i32,
        y: i32,
    },
    Move {
        x: i32,
        y: i32,
    },
    Drag {
        path: Vec<CoordinatePair>,
    },
    Scroll {
        x: i32,
        y: i32,
        direction: String,
        amount: i32,
    },
    Keypress {
        keys: Vec<String>,
    },
    Type {
        text: String,
    },
    Screenshot {},
    Wait {
        ms: u32,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CoordinatePair {
    pub x: i32,
    pub y: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafetyCheck {
    pub id: String,
    pub code: String,
    pub message: String,
}

// ============================================================================
// Common Types
// ============================================================================

/// Status of an output item.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum OutputStatus {
    #[default]
    Completed,
    InProgress,
    Failed,
}

/// Role for output messages.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum OutputRole {
    Assistant,
}

// ============================================================================
// Configuration Types
// ============================================================================

/// Reasoning configuration for o-series models.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ReasoningConfig {
    /// Reasoning effort level
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<ReasoningEffort>,
    /// Whether to include summary
    #[serde(skip_serializing_if = "Option::is_none")]
    pub summary: Option<ReasoningSummaryConfig>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ReasoningEffort {
    Low,
    Medium,
    High,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ReasoningSummaryConfig {
    Auto,
    Concise,
    Detailed,
}

/// Text format configuration.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TextConfig {
    pub format: TextFormat,
}

/// Text format options.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TextFormat {
    #[serde(rename = "type")]
    pub format_type: TextFormatType,
    /// JSON schema for json_schema format
    #[serde(skip_serializing_if = "Option::is_none")]
    pub json_schema: Option<Value>,
}

#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TextFormatType {
    #[default]
    Text,
    JsonObject,
    JsonSchema,
}

/// Truncation strategy.
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Truncation {
    #[default]
    Disabled,
    Auto,
}

// ============================================================================
// Usage Statistics
// ============================================================================

/// Token usage statistics.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Usage {
    pub input_tokens: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub input_tokens_details: Option<InputTokensDetails>,
    pub output_tokens: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_tokens_details: Option<OutputTokensDetails>,
    pub total_tokens: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct InputTokensDetails {
    #[serde(default)]
    pub cached_tokens: u32,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct OutputTokensDetails {
    #[serde(default)]
    pub reasoning_tokens: u32,
}

// ============================================================================
// Deletion Response
// ============================================================================

/// Deletion response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeleteResponse {
    pub id: String,
    pub object: &'static str,
    pub deleted: bool,
}

impl DeleteResponse {
    pub const OBJECT: &'static str = "response";
}

// ============================================================================
// Input Items List Response
// ============================================================================

/// Response for GET /v1/responses/{id}/input_items
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InputItemsResponse {
    pub object: &'static str,
    pub data: Vec<Value>,
    pub first_id: Option<String>,
    pub last_id: Option<String>,
    pub has_more: bool,
}

impl InputItemsResponse {
    pub const OBJECT: &'static str = "list";
}
