/**
 * E2E tests for image generation display.
 *
 * Tests that images generated by zimage_turbo are properly displayed
 * in the chat UI with the correct container file URLs.
 */

import { test, expect } from '@playwright/test';

test.describe('Image Generation', () => {
	test('displays generated images from zimage_turbo', async ({ page }) => {
		test.setTimeout(180000); // Image generation takes longer (model does multiple tool calls)

		// Capture ALL console logs for debugging (filtering was losing important data)
		const consoleLogs: string[] = [];
		page.on('console', (msg) => {
			consoleLogs.push(`[${msg.type()}] ${msg.text()}`);
		});

		// Also capture page errors
		page.on('pageerror', (error) => {
			consoleLogs.push(`[PAGE ERROR] ${error.message}`);
		});

		// Start fresh - go to home page and navigate to a new conversation page
		// This avoids the mid-streaming navigation issue
		await page.goto('/');

		// Click "New Chat" to ensure we're in a fresh state and get a conversation URL
		const newChatButton = page.getByRole('button', { name: 'New Chat' }).first();
		await newChatButton.click();
		await page.waitForTimeout(500);

		// Wait for navigation to conversation page
		await page.waitForURL(/\/c\//, { timeout: 5000 }).catch(() => {
			// If not navigated to conversation, that's fine - we're on home page
		});

		const textarea = page.locator('textarea[placeholder="Message Strieber GPT..."]');
		const sendButton = page.getByTestId('send-button');

		// Request image generation - be VERY specific to prevent the model from looping
		// We tell it exactly what to do so it doesn't keep trying variations
		await textarea.fill('Run this exact Python code once: import matplotlib.pyplot as plt; fig, ax = plt.subplots(); ax.add_patch(plt.Circle((0.5,0.5), 0.3, color="red")); ax.set_xlim(0,1); ax.set_ylim(0,1); ax.set_aspect("equal"); plt.show()');
		await sendButton.click();

		// Wait for streaming to complete
		// Strategy: Wait for the send button to be enabled (not disabled) - this indicates streaming finished
		// and the UI is ready for new input
		const stopButton = page.getByTestId('stop-button');

		// First wait for streaming to START (stop button appears)
		try {
			await expect(stopButton).toBeVisible({ timeout: 15000 });
			console.log('[TEST] Stop button visible - streaming started');
		} catch {
			console.log('[TEST] Stop button did not appear in 15s - checking if response exists');
			// Print console logs immediately for debugging
			console.log('[TEST] === Early Console Logs ===');
			consoleLogs.forEach((log) => console.log(log));
		}

		// Wait for the generated image to appear (more robust than checking button state)
		// The image will have a container file URL
		const generatedImage = page.locator('img[src*="/containers/"]').first();

		try {
			await expect(generatedImage).toBeVisible({ timeout: 150000 });
			console.log('[TEST] Generated image is now visible');
		} catch (e) {
			// Print console logs on failure
			console.log('[TEST] === Console Logs before timeout ===');
			consoleLogs.forEach((log) => console.log(log));
			throw e;
		}

		// Give a moment for the UI to stabilize
		await page.waitForTimeout(1000);

		// Dump all images on page for debugging
		const allImages = await page.locator('img').all();
		console.log(`[TEST] Found ${allImages.length} images on page:`);
		for (let i = 0; i < allImages.length; i++) {
			const src = await allImages[i].getAttribute('src');
			const alt = await allImages[i].getAttribute('alt');
			console.log(`[TEST]   img[${i}]: src="${src?.slice(0, 100)}..." alt="${alt}"`);
		}

		// Output console logs for debugging
		console.log('=== Browser Console Logs ===');
		consoleLogs.forEach((log) => console.log(log));
		console.log(`=== End Console Logs (${consoleLogs.length} captured) ===`);

		// Verify image has a container file URL (generatedImage locator defined above)
		const src = await generatedImage.getAttribute('src');
		expect(src).toBeTruthy();
		expect(src).toContain('/containers/');
		expect(src).toContain('/files/');
		expect(src).toContain('/content');

		console.log(`[TEST] Image URL verified: ${src?.slice(0, 80)}...`);

		// Take screenshot for visual verification
		await page.screenshot({
			path: 'test-results/screenshots/image-generation.png',
			fullPage: true
		});
	});
});
